# Generated by Django 6.1 on 2026-08-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelstation',
            name='created_at',
        ),
    ]
